from dotenv import load_dotenv
import os

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

if not GROQ_API_KEY:
    raise RuntimeError(
        "GROQ_API_KEY is not set. Copy .env.example to .env in the project "
        "root and add your key (get one at https://console.groq.com/keys)."
    )

# Model + behavior are overridable via environment variables.
MODEL_NAME = os.getenv("MODEL_NAME", "openai/gpt-oss-120b")

# Small, non-reasoning model used ONLY to decide "does this message need a
# web search" (see _decide_and_search in groq_service.py). gpt-oss-120b is a
# reasoning model -- it "thinks" before every reply, even a yes/no one --
# which made that decision step slow enough to noticeably delay every
# message. llama-3.1-8b-instant has no thinking phase and still supports
# tool calling, so the routing decision comes back much faster. The real
# answer is still generated by MODEL_NAME above, unchanged.
#
# NOTE: this previously defaulted to "openai/gpt-oss-20b", which is ALSO a
# reasoning model -- it still "thinks" before deciding whether to search,
# which is exactly the extra latency this router was supposed to avoid.
# llama-3.1-8b-instant is the model actually described above: no thinking
# phase, still supports tool calling, ~560 tokens/sec on Groq.
ROUTER_MODEL_NAME = os.getenv("ROUTER_MODEL_NAME", "llama-3.1-8b-instant")

MAX_HISTORY_MESSAGES = int(os.getenv("MAX_HISTORY_MESSAGES", "20"))

# Public deployment protection.
RATE_LIMIT_MAX_REQUESTS = int(os.getenv("RATE_LIMIT_MAX_REQUESTS", "20"))
RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("RATE_LIMIT_WINDOW_SECONDS", "60"))

# Allowed frontend origins.
ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,https://vextai.netlify.app",
    ).split(",")
    if origin.strip()
]

# Web search (Tavily). AUTO_WEB_SEARCH_ENABLED is a kill switch: set it to
# "false" to stop the model from ever calling the search tool on its own,
# without touching code. It's a no-op either way if TAVILY_API_KEY isn't set
# -- the model just answers from its own knowledge, no error.
AUTO_WEB_SEARCH_ENABLED = os.getenv("AUTO_WEB_SEARCH_ENABLED", "true").lower() == "true"
WEB_SEARCH_MAX_RESULTS = int(os.getenv("WEB_SEARCH_MAX_RESULTS", "5"))
